// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportLink.Data;

#nullable disable

namespace SportLink.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SportLink.Entidades.Cancha", b =>
                {
                    b.Property<int>("CanchaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CanchaId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("SportLink.Entidades.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("LigaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaId");

                    b.HasIndex("LigaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SportLink.Entidades.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("EquipoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SportLink.Entidades.FechaTorneo", b =>
                {
                    b.Property<int>("FechaTorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("FechaTorneoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("FechasTorneo");
                });

            modelBuilder.Entity("SportLink.Entidades.Liga", b =>
                {
                    b.Property<int>("LigaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LigaId");

                    b.ToTable("Ligas");
                });

            modelBuilder.Entity("SportLink.Entidades.Partido", b =>
                {
                    b.Property<int>("PartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArbitroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanchaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipoVisitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("FechaTorneoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("PartidoId");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("FechaTorneoId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("SportLink.Entidades.Resultado", b =>
                {
                    b.Property<int>("ResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargadoPorUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartidoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResultadoId");

                    b.HasIndex("CargadoPorUsuarioId");

                    b.HasIndex("PartidoId")
                        .IsUnique();

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("SportLink.Entidades.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SportLink.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SportLink.Entidades.Categoria", b =>
                {
                    b.HasOne("SportLink.Entidades.Liga", "Liga")
                        .WithMany("Categorias")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("SportLink.Entidades.Equipo", b =>
                {
                    b.HasOne("SportLink.Entidades.Categoria", "Categoria")
                        .WithMany("Equipos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SportLink.Entidades.FechaTorneo", b =>
                {
                    b.HasOne("SportLink.Entidades.Categoria", "Categoria")
                        .WithMany("FechasTorneo")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SportLink.Entidades.Partido", b =>
                {
                    b.HasOne("SportLink.Entidades.Usuario", "Arbitro")
                        .WithMany("PartidosArbitrados")
                        .HasForeignKey("ArbitroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportLink.Entidades.Cancha", "Cancha")
                        .WithMany("Partidos")
                        .HasForeignKey("CanchaId");

                    b.HasOne("SportLink.Entidades.Equipo", "EquipoLocal")
                        .WithMany("PartidosComoLocal")
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportLink.Entidades.Equipo", "EquipoVisitante")
                        .WithMany("PartidosComoVisitante")
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportLink.Entidades.FechaTorneo", "FechaTorneo")
                        .WithMany("Partidos")
                        .HasForeignKey("FechaTorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arbitro");

                    b.Navigation("Cancha");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("FechaTorneo");
                });

            modelBuilder.Entity("SportLink.Entidades.Resultado", b =>
                {
                    b.HasOne("SportLink.Entidades.Usuario", "CargadoPorUsuario")
                        .WithMany("ResultadosCargados")
                        .HasForeignKey("CargadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportLink.Entidades.Partido", "Partido")
                        .WithOne("Resultado")
                        .HasForeignKey("SportLink.Entidades.Resultado", "PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargadoPorUsuario");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SportLink.Entidades.Usuario", b =>
                {
                    b.HasOne("SportLink.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SportLink.Entidades.Cancha", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("SportLink.Entidades.Categoria", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("FechasTorneo");
                });

            modelBuilder.Entity("SportLink.Entidades.Equipo", b =>
                {
                    b.Navigation("PartidosComoLocal");

                    b.Navigation("PartidosComoVisitante");
                });

            modelBuilder.Entity("SportLink.Entidades.FechaTorneo", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("SportLink.Entidades.Liga", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("SportLink.Entidades.Partido", b =>
                {
                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("SportLink.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SportLink.Entidades.Usuario", b =>
                {
                    b.Navigation("PartidosArbitrados");

                    b.Navigation("ResultadosCargados");
                });
#pragma warning restore 612, 618
        }
    }
}
