<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="Servicios\" />
    <Folder Include="wwwroot\img\ligas\" />
    <Folder Include="wwwroot\img\generales\" />
    <Folder Include="wwwroot\img\usuarios\" />
    <Folder Include="wwwroot\img\arbitros\" />
    <Folder Include="wwwroot\img\equipos\" />
    <Folder Include="wwwroot\img\noticias\" />
    <Folder Include="wwwroot\img\jugadores\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
